#!/usr/bin/env bash
# generate-config.sh
# Generates a Helm values override file for deploying cloudquery-sync to
# AKS or GKE. Run this script before `helm install`/`helm upgrade`.
#
# Usage:
#   ./scripts/generate-config.sh --platform aks --namespace cloudquery --output /tmp/values-generated.yaml
#   ./scripts/generate-config.sh --platform gke --project my-gcp-project --sa-email cq@my-gcp-project.iam.gserviceaccount.com
#
# Requirements: bash >= 4, kubectl (authenticated to the target cluster)

set -euo pipefail
IFS=$'\n\t'
NAMESPACE="cloudquery"
OUTPUT_FILE="values-generated.yaml"
RELEASE_NAME="cloudquery-sync"
MODE="cronjob"
SCHEDULE="0 * * * *"

# GKE-specific
GCP_PROJECT=""
GCP_SA_EMAIL=""
GKE_DATASET="cloudquery_k8s"

# AKS-specific
AKS_RESOURCE_GROUP=""
AKS_CLUSTER_NAME=""
AZURE_WORKLOAD_IDENTITY_CLIENT_ID=""

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
usage() {
  cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --platform          Target platform: aks | gke  (required)
  --namespace         Kubernetes namespace          (default: cloudquery)
  --output            Output values file path       (default: values-generated.yaml)
  --release           Helm release name             (default: cloudquery-sync)
  --mode              cronjob | deployment          (default: cronjob)
  --schedule          CronJob schedule expression   (default: "0 * * * *")

GKE options:
  --project           GCP project ID               (required for gke)
  --sa-email          GCP service account email for Workload Identity
  --dataset           BigQuery dataset ID           (default: cloudquery_k8s)

AKS options:
  --resource-group    AKS resource group
  --cluster-name      AKS cluster name
  --client-id         Azure Workload Identity client ID

  -h, --help          Show this help message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --platform)        PLATFORM="$2";                    shift 2 ;;
    --namespace)       NAMESPACE="$2";                   shift 2 ;;
    --output)          OUTPUT_FILE="$2";                 shift 2 ;;
    --release)         RELEASE_NAME="$2";                shift 2 ;;
    --mode)            MODE="$2";                        shift 2 ;;
    --schedule)        SCHEDULE="$2";                    shift 2 ;;
    --project)         GCP_PROJECT="$2";                 shift 2 ;;
    --sa-email)        GCP_SA_EMAIL="$2";                shift 2 ;;
    --dataset)         GKE_DATASET="$2";                 shift 2 ;;
    --resource-group)  AKS_RESOURCE_GROUP="$2";          shift 2 ;;
    --cluster-name)    AKS_CLUSTER_NAME="$2";            shift 2 ;;
    --client-id)       AZURE_WORKLOAD_IDENTITY_CLIENT_ID="$2"; shift 2 ;;
    -h|--help)         usage; exit 0 ;;
    *)                 echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
if [[ -z "$PLATFORM" ]]; then
  echo "ERROR: --platform is required (aks or gke)" >&2
  usage
  exit 1
fi

if [[ "$PLATFORM" != "aks" && "$PLATFORM" != "gke" ]]; then
  echo "ERROR: --platform must be 'aks' or 'gke'" >&2
  exit 1
fi

if [[ "$MODE" != "cronjob" && "$MODE" != "deployment" ]]; then
  echo "ERROR: --mode must be 'cronjob' or 'deployment'" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Generate values file
# ---------------------------------------------------------------------------
echo "Generating values for platform=${PLATFORM}, mode=${MODE}, namespace=${NAMESPACE}"

cat > "${OUTPUT_FILE}" <<YAML
# Auto-generated by scripts/generate-config.sh
# Platform: ${PLATFORM}
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Review and customise before deploying.

mode: ${MODE}

YAML

# CronJob settings
if [[ "$MODE" == "cronjob" ]]; then
  cat >> "${OUTPUT_FILE}" <<YAML
cronJob:
  schedule: "${SCHEDULE}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

YAML
fi

# Platform-specific ServiceAccount annotations
if [[ "$PLATFORM" == "gke" ]]; then
  if [[ -z "$GCP_PROJECT" ]]; then
    echo "WARNING: --project not set. Set GCP_PROJECT in the generated values before deploying." >&2
    GCP_PROJECT="<your-gcp-project>"
  fi
  SA_ANNOTATIONS=""
  if [[ -n "$GCP_SA_EMAIL" ]]; then
    SA_ANNOTATIONS="    iam.gke.io/gcp-service-account: ${GCP_SA_EMAIL}"
  fi

  cat >> "${OUTPUT_FILE}" <<YAML
serviceAccount:
  create: true
  annotations:
${SA_ANNOTATIONS:-    # iam.gke.io/gcp-service-account: cq-sync@${GCP_PROJECT}.iam.gserviceaccount.com}

# Example BigQuery destination for GKE
# Uncomment and fill in to use BigQuery as the destination.
# destination:
#   name: bigquery
#   path: cloudquery/bigquery
#   version: "v4.0.0"
#   spec:
#     project_id: "${GCP_PROJECT}"
#     dataset_id: "${GKE_DATASET}"

YAML

elif [[ "$PLATFORM" == "aks" ]]; then
  CLIENT_ID_VALUE="${AZURE_WORKLOAD_IDENTITY_CLIENT_ID:-<your-azure-client-id>}"

  cat >> "${OUTPUT_FILE}" <<YAML
serviceAccount:
  create: true
  annotations:
    azure.workload.identity/client-id: "${CLIENT_ID_VALUE}"

podLabels:
  azure.workload.identity/use: "true"

# Example PostgreSQL destination for AKS
# Uncomment and fill in to use Azure PostgreSQL as the destination.
# destination:
#   name: postgresql
#   path: cloudquery/postgresql
#   version: "v8.0.0"
#   spec:
#     connection_string: "postgresql://user:pass@host.postgres.database.azure.com:5432/cloudquery?sslmode=require"

YAML
fi

# Common placeholder destination values
cat >> "${OUTPUT_FILE}" <<YAML
# Source configuration
source:
  tables:
    - "k8s_*"
  # skip_tables:
  #   - "k8s_core_secrets"
  spec:
    discovery_filter: all

# Resources (tune based on cluster size)
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
YAML

echo ""
echo "Generated: ${OUTPUT_FILE}"
echo ""
echo "Next steps:"
echo "  1. Review and edit ${OUTPUT_FILE}"
echo "  2. Fill in destination configuration"
echo "  3. helm upgrade --install ${RELEASE_NAME} charts/cloudquery-sync \\"
echo "       --namespace ${NAMESPACE} --create-namespace \\"
echo "       -f ${OUTPUT_FILE}"
